
openapi: 3.0.0

paths:
  /user/{userId}:
    get:
      summary: This endpoint returns a user
      parameters:
        - name: userId
          in: path
          required: true
          description: user ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getUser/invocations"
        httpMethod: "POST"
    put:
      summary: This endpoint saves a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                age:
                  type: string
                name:
                  type: string
                last_name:
                  type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putUser/invocations"
        httpMethod: "POST"
